### PR TITLE
Password complexity added

### LINKED ISSUE #4: User can create account with very insecure password
Portal don't require password length and complexity.

### PR DESCRIPTION
**Pull request by sharvil1205**
this commit fixes #4 
I have added the following features to the register.jsp and updateProfile.jsp files:
1. Added the 'Show Password' feature.
2. Password gets accepted only if it contains at least one: number, upper case character, lower case character, special character, and password length should be 8 or more.

### CODE REVIEW

**Comment by sharvil1205** [comment]
I changed only 2 files. I don't know why it is showing 8 files changed.

**Comment by jaygajera17** [comment]
@sharvil1205 it seems like you deleted _pom.xml_ file !! , and it is working properly have you tested?

**Comment by sharvil1205** [comment]
@jaygajera17 I only updated 2 files register.jsp and updateProfile.jsp. But due to a glitch similar to [this](https://stackoverflow.com/questions/55479729/github-pull-request-shows-wrong-diff) it shows 8 files updated. Since you can edit this, can you do something about the remaining 6 files?

I have tested changes on the 2 password files, they are working properly.

**Comment by jaygajera17** [comment]
@sharvil1205 
sorry i am not allow  to change your commits, send pull request again for only those change files

**Pull request closed without merging**
